GET  http://127.0.0.1:3000/api/json/cart/shopindex HTTP/1.1
Content-Type: application/json
token:'EScWGhXzhW1frc8fToeZVO3EGVVRK3sEkOL/e9cPSCQ4+osAXeZfdCV8M/hht1fJF3TB8hAHV5nWNffFe9BceBJKwPtgMu3gMJv0ULZ+OCOLEGgPsfjp1G63mqOqeWBBl8gwUivltzmOFUpx1yVsvFlmM9vUWELd0GgKWI5N7AE='